openapi: '3.0.2'
info:
  title: Statistiques
  description: API pour la gestion des statistiques utilisateurs pour le projet Asteroids Warrior
  version: '1.0'
servers:
  - url: https://stats.aw.alexandre-vogel.fr/


tags:
  - name: Statistiques
    description: Ensemble des fonctions liées à l'obtention et la modification des statistiques des utilisateurs
  - name: Classement
    description: Ensemble des fonctions liées à l'obtention du classement des utilisateurs

paths:
  /stats:
    get:
      tags :
        - Statistiques
      summary: Récupère les statistiques de tous les utilisateurs
      description: Récupère les statistiques de tous les utilisateurs.
      responses: 
        '200':
          description: L'ensemble du classement a été récupéré et est transmis dans le corps du message
          content:
            json:
              schema:
                description: Ensemble des statistiques
                $ref: '#/components/schemas/arrayOfUserStats'
        '500':
          description: "Erreur interne au serveur"


  /stats/{username}:
    get:
      tags:
        - Statistiques
      summary: Récupère les statistiques d'un utilisateur particulier
      description: Récupère les statistiques d'un utilisateur particulier.
      parameters: 
        - name: username
          in: path
          description: Username de l'utilisateur
          required: true
          schema:
            type: string
      responses:
        '200':
          description: L'ensemble des statistiques utilisateur avec l'username spécifié ont été récupérées
          content:
            json:
              schema:
                $ref: '#/components/schemas/userStats'
        '404':
          description: L'utilisateur demandé n'a pas été trouvé
        '500':
          description: "Erreur interne au serveur"

    post:
      tags:
        - Statistiques
      summary: Modifie les statistiques d'un utilisateur particulier
      description: |
                    Modifie les statistiques d'un utilisateur particulier : les statistiques 
                    renseignées dans le corps de la requête seront additionnées à celles 
                    existantes pour l'utilisateur concerné.
      parameters: 
        - in: header
          name: serverToken
          schema:
            type: string
          required: true
          description: Token pour identifier le serveur
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: Nom de l'utilisateur concerné
      responses:
        '200':
          description: Les statistiques ont bien été envoyées
        '400':
          description: 'Requête invalide : vérifiez la syntaxe'
        '403':
          description: Vous n'êtes pas autorisé à modifier les statistiques
        '404':
          description: L'utilisateur demandé n'a pas été trouvé
        '500':
          description: "Erreur interne au serveur"

    delete:
      tags:
        - Statistiques
      summary: Réinitialise les statistiques d'un utilisateur particulier
      description: |
                    Réinitialise les statistiques d'un utilisateur particulier : les statistiques 
                    de l'utilisateur concerné seront remises à 0.
      parameters:
        - in: header
          name: serverToken
          schema:
            type: string
          required: true
          description: Token pour identifier le serveur
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: Nom de l'utilisateur concerné
      responses:
        '200':
          description: Les statistiques ont bien été réinitialisées
        '400':
          description: 'Requête invalide : vérifiez la syntaxe'
        '403':
          description: Vous n'êtes pas autorisé à modifier les statistiques
        '404':
          description: L'utilisateur demandé n'a pas été trouvé
        '500':
          description: "Erreur interne au serveur"


  /ranking:
    get:
      tags:
        - Classement
      summary: Récupère le classement des utilisateurs en fonction de leur nombre de points
      description: Récupère le classement des utilisateurs en fonction de leur nombre de points.
      parameters:
        - in: query
          name: offset
          schema:
            type: number
            minimum: 1
          required: false
          description: Rang du premier utilisateur du classement
        - in: query
          name: limit
          schema:
            type: number
            minimum: 1
          required: false
          description: Taille du classement
      responses:
        '200':
          description: Le classement a été récupéré et est transmis dans le corps du message
          content:
            json:
              schema:
                description: Classement des utilisateurs
                $ref: '#/components/schemas/arrayOfUserStats'
        '400':
          description: "Requête invalide : l'un des champs est incorrect"
        '500':
          description: "Erreur interne au serveur"
        

  /ranking/{stat}:
    get:
      tags:
        - Classement
      summary: Récupère le classement des utilisateurs en fonction d'une statistique particulière
      description: Récupère le classement des utilisateurs en fonction d'une statistique particulière.
      parameters:
        - in: path
          name: stat
          schema:
            type: string
          required: true
          description: Statistique sur laquelle doit être basée le classement
        - in: query
          name: offset
          schema:
            type: number
            minimum: 1
          required: false
          description: Rang du premier utilisateur du classement
        - in: query
          name: limit
          schema:
            type: number
            minimum: 1
          required: false
          description: Taille du classement
      responses:
        '200':
          description: Le classement a été récupéré et est transmis dans le corps du message
          content:
            json:
              schema:
                description: Classement des utilisateurs
                $ref: '#/components/schemas/arrayOfUserStats'
        '400':
          description: "Requête invalide : l'un des champs est incorrect"
        '500':
          description: "Erreur interne au serveur"

components:
  schemas:
    userStats:
      type: object
      properties:
        username:
          type: string
        nbPoints:
          type: number
          minimum: 0
        nbKills:
          type: number
          minimum: 0
        nbAsteroids:
          type: number
          minimum: 0
        nbDeaths:
          type: number
          minimum: 0
        nbPowerUps:
          type: number
          minimum: 0
        nbGames:
          type: number
          minimum: 0
        nbWins:
          type: number
          minimum: 0
        maxKills:
          type: number
          minimum: 0
        maxPoints:
          type: number
          minimum: 0
        maxPowerUps:
          type: number
          minimum: 0
        maxDeaths:
          type: number
          minimum: 0
      example:
        username: toto
        nbPoints: 2921213
        nbKills: 1021
        nbAsteroids: 39281
        nbDeaths: 2012
        nbPowerUps: 821
        nbGames: 210
        nbWins: 102
        maxKills: 13
        maxPoints: 768
        maxPowerUps: 11
        maxDeaths: 23

    arrayOfUserStats:
      type: array
      items:
        $ref: '#/components/schemas/userStats'
      example:
        - username: toto
          nbPoints: 2921213
          nbKills: 1021
          nbAsteroids: 39281
          nbDeaths: 2012
          nbPowerUps: 821
          nbGames: 210
          nbWins: 102
          maxKills: 13
          maxPoints: 768
          maxPowerUps: 11
          maxDeaths: 23
        - username: titi
          nbPoints: 221513
          nbKills: 121
          nbAsteroids: 9281
          nbDeaths: 212
          nbPowerUps: 321
          nbGames: 100
          nbWins: 42
          maxKills: 9
          maxPoints: 421
          maxPowerUps: 6
          maxDeaths: 26
